spring.datasource.url: jdbc:mysql://localhost:3306/blog1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username: root
spring.datasource.password: 12345
spring.jpa.hibernate.ddl-auto: none
spring:
  liquibase:
    change-log:
      classpath: db/changelog/db.changelog-master.xml

#liquibase:
#  change-log:
#    classpath: db/changelog/db.changelog-master.xml

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005
